    # HTTP反向代理相关配置开始 <<<
     # 屏蔽恶意UA
    if ($remote_user ~ ".+") {
        return 444;
    }
    #拦截常见恶意 User-Agent
    if ($http_user_agent ~* (curl|python|sqlmap|scanner|masscan|nikto|nmap|dirbuster|gobuster|wappalyzer|sqlin|zgrab|acunetix|nessus|arachni)) {
        return 444;
    }
    #禁止访问以 . 开头的文件
    location ~ /\. {
        return 444;
    }
    # 拒绝含有常见注入关键字的请求
    if ($request_uri ~* "\?(.*)(select|union|extractvalue|updatexml|concat|information_schema|sleep\()") {
        return 444;
    }
    # 禁止传递数组参数攻击
    if ($query_string ~* "\[|\]|\.\.|@|%27|%22|%0A") {
        return 444;
    }
    if ($request_uri ~* "(%0[0-9a-cA-Ce-fE-F]|%1[0-9a-fA-F]|%2e%2e|%252e)") {
        return 444;
    }
    #限制请求方法
    if ($request_method !~ ^(GET|POST)$) {
        return 444;
    }
     #屏蔽包含 <script>、javascript:、data: 等恶意 payload 的 URL
    if ($request_uri ~* "<script>|data:text|javascript:|base64|constructor|alert\(|onerror=|onload=") {
        return 444;
    }
    # 拦截常见 WebShell / 扫描器 / 漏洞利用特征 URI
    if ($request_uri ~* "(eval-stdin\.php|allow_url_include|java|actuator|base-service|auto_prepend_file|php:\/\/input|%ADd\+allow_url_include|system|/containers/json|/phpunit|/vendor/phpunit|springboot|/thinkphp|invokefunction|Runtime|call_user_func_array|base64_decode\(|system\(|shell_exec\(|\.\./\.\./)") {
        return 444;
    }
    # 禁止 .jsp / php / asp / py / sh 等文件
    if ($request_uri ~* \.(jsp|jspx|php|asp|aspx|py|sh|bash|exe|dll|bat|cmd|bak)$) {
        return 444;
    }
    # 拦截管理后台和扫描目录
    if ($request_uri ~* ^/(admin|administrator|user/login|register|wp-admin|wp-includes|cgi-bin|ALFA_DATA|console|shell)) {
        return 444;
    }
    # 拦截敏感文件
    if ($request_uri ~* (xmlrpc\.php|wp-config\.php|install\.php|readme\.html|license\.txt|fckeditor|tiny_mce|ckeditor|\.env|\.git)) {
        return 444;
    }
    # 屏蔽探测路径
    if ($request_uri ~* /(wiki|phpmyadmin|pma|phpunit|vendor|install|setup-config|readme\.html|license\.txt)) {
        return 444;
    }
    # 禁止压缩文件
    if ($request_uri ~* \.(gz|zip|rar|7z|tar|bz2|xz|tgz)$) {
        return 444;
    }
    #拦截一些不存在的路径
    location ~ ^/(api|sites|javascript|redirect) {
        return 444;
    }   