
[INCLUDES]

before = iptables-ipset-proto6.conf

[Definition]

# path to configuration of nginx (used to target nginx-instance in multi-instance system,
# and as path for the blacklisted map):
srv_cfg_path = /www/server/panel/vhost/nginx/

# cmd-line arguments to supply to test/reload nginx:
#srv_cmd = nginx -c %(srv_cfg_path)s/nginx.conf
srv_cmd = /www/server/nginx/sbin/nginx

# pid file (used to check nginx is running):
srv_pid = /www/server/nginx/logs/nginx.pid

# command used to check whether nginx is running and configuration is valid:
srv_is_running = pgrep -x nginx > /dev/null
srv_check_cmd = %(srv_is_running)s && %(srv_cmd)s -t

# first test nginx is running and configuration is correct, hereafter send reload signal:
blck_lst_reload = %(srv_cmd)s -s reload

# map-file for nginx, can be redefined using `action = nginx-block-map[blck_lst_file="/path/file.map"]`:
blck_lst_file = %(srv_cfg_path)s/blockip-<name>.conf


# Action definition:

actionstart_on_demand = false
actionstart = ipset -exist create <ipmset> <ipsettype> timeout <default-ipsettime> maxelem <maxelem> <familyopt>
              <_ipt_add_rules>
			  touch '%(blck_lst_file)s'

actionflush = ipset flush <ipmset>
              truncate -s 0 '%(blck_lst_file)s'; %(blck_lst_reload)s

actionstop = <_ipt_del_rules>
             <actionflush>
             ipset destroy <ipmset> 2>/dev/null || { sleep 1; ipset destroy <ipmset>; }

deny_rule = deny <fid>;
_echo_blck_row = echo "%(deny_rule)s"

actionban = ipset -exist add <ipmset> <ip> timeout <ipsettime>
			grep -qF "%(deny_rule)s" '%(blck_lst_file)s' || (%(_echo_blck_row)s >> '%(blck_lst_file)s'; %(blck_lst_reload)s)

actionunban = ipset -exist del <ipmset> <ip>
			  id=$(%(_echo_blck_row)s | sed -e 's/[]\/$*.^|[]/\\&/g'); sed -i "/^$id$/d" %(blck_lst_file)s; %(blck_lst_reload)s
